### PR TITLE
Change AbstractCharonException to RuntimeException for better usability

### PR DESCRIPTION
**Pull request by Captain-P-Goldfish**
I got no information about that this pull request was not accepted the last time but the change is not present in the current maven-central version. So once again

### CODE REVIEW

**Comment by madurangasiriwardena** [comment]
Resolves https://github.com/wso2/charon/issues/121

**Comment by Captain-P-Goldfish** [comment]
excuse me, but aren't you going to accept this request?

**Comment by madurangasiriwardena** [comment]
Hi @Captain-P-Goldfish,

Thank you for your contribution and sorry for the late reply.

But it is not good to change a Exception to RuntimeException simply because its hard to catch. See this [tutorial](https://docs.oracle.com/javase/tutorial/essential/exceptions/runtime.html) from Java documentation which explains the usage of each type in each scenario. Please discuss the original issue you have over dev@wso2.org mailing list to find a proper solution.

**Comment by omindu** [comment]
In this sort of situations we can follow an approach similar to [1] which helps you to deal with checked exceptions. 

[1] - https://stackoverflow.com/questions/27644361/how-can-i-throw-checked-exceptions-from-inside-java-8-streams/27644392#27644392

**Comment by Captain-P-Goldfish** [comment]
I will try to ask on the mailing list. But this is actually not a trivial request. charon is making heavily overuse of checked exceptions which carries a lot of unnecessary exception handling.
I would reference the Book "Effective Java" here with item 59 "Avoid unnecessary use of checked exceptions"

**Comment by ruwanta** [comment]
Charon is used by folks who uses lambda as well as folks using of checked exceptions. There are two camps who prefer checked exception and who hates.
I believe checked exception is good so that programmer can handle the errors knowingly, without surprise at the runtime where the exception is caught and unhandled. 
Since this is a library used by folks from the both camps, I prefer keeping the old style for consistency.

Also alternative exists to use "wrapper"to help checked exception handling.
e.g. [LambdaExceptionUtils ](https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-core/org.wso2.carbon.identity.core/src/main/java/org/wso2/carbon/identity/core/util/LambdaExceptionUtils.java)

Hence -1 on the proposed change.

**Comment by nuwandiw** [comment]
Closing the PR according to above comment. @Captain-P-Goldfish Thank you for the contribution. We highly appreciate your interest on the project.

**Pull request closed without merging**
