### PR TITLE
Add group member helper to retrieve IDs of members

### PR DESCRIPTION
**Pull request by Captain-P-Goldfish**
to retrieve a list of the IDs of a group a method was added that will extract the member ids based on their type-value

### CODE REVIEW

**Comment by Captain-P-Goldfish** [comment]
Now I am really finished with this branch :-)
would be great if this gets also merged today :-)

**Comment by ashensw** [comment]
@Captain-P-Goldfish The build([Travis-ci)](https://travis-ci.org/wso2/charon/builds/450820900?utm_source=github_status&utm_medium=notification) is failing. Can you please check?

**Comment by Captain-P-Goldfish** [comment]
checkstyle...
would be easier if you would provide checkstyle.xml and formatter.xml in the repository

**Comment by Captain-P-Goldfish** [comment]
Travis-ci build does now succeed.

**Pull request merged**
