### PR TITLE
Make value as mandatory when add member to group

### PR DESCRIPTION
**Pull request by nilasini**
## Purpose
Resolves https://github.com/wso2/product-is/issues/9619

Make the value sub-attribute as a required attribute. Please check [1] for more details
[1] https://github.com/wso2/product-is/issues/9619#issuecomment-760758080

### CODE REVIEW

**Review by emswbandara — APPROVED** [review]

**Comment by IsuraD** [comment]
Is this backward compatible?

**Comment by nilasini** [comment]
No. Previously when we send a group creation request without member value, group creation will be done but members will not be added, but now group creation also will not happen we will get  400 bad request since a required attribute is missing.  

Is it necessary to make it backward compatible through a config?

**Comment by IsuraD** [comment]
> No. Previously when we send a group creation request without member value, group creation will be done but members will not be added, but now group creation also will not happen we will get 400 bad request since a required attribute is missing.
> 
> Since the current approach is the correct way, is it necessary to make it backward compatible through a config?

You meant.. existing implementation is also having some an issue. So, we don't need a config.

**Comment by nilasini** [comment]
Started PR builder. Once it passed will merge it.

**Pull request merged**
