### PR TITLE
Support dynamic endpoint extensions

### PR DESCRIPTION
**Pull request by Captain-P-Goldfish**
Up until now it was relatively complicated to add additional SCIM endpoints if some were required. I have rebuild the codebase of charon by removing the UserManager and exchange it for the ResourceHandler.
Additionally I extended the bulk-endpoint implementation so that there also additional endpoints can be referenced and called.

### CODE REVIEW

**Comment by Captain-P-Goldfish** [comment]
fixes  #181

**Comment by Captain-P-Goldfish** [comment]
Sorry but I definetly will not fix the last find-bugs issue... this is just too stupid -_-

**Comment by DMHP** [comment]
@Captain-P-Goldfish , This PR is merged to the dynamic_endpoint_extensions feature branch which is created from the master branch. After reviewing the code and some testing cycles, we will move the code to the master branch. We really appreciate your contribution.

**Comment by DMHP** [comment]
@Captain-P-Goldfish , Our plan is to merge the PRs to the branch 'dynamic_endpoint_extensions' and after doing some code reviews and test cycles to move the whole code to the master branch. So we really appreciate if you can contribute working on resolving conflicts in order to merge this PR to 'dynamic_endpoint_extensions' branch. We have already merged https://github.com/wso2/charon/pull/219 to the above branch.

**Comment by Captain-P-Goldfish** [comment]
I have already merged all my branches into a single one. Would you be okay if I would provide this branch as an alternative? Would make the following work easier.

**Comment by Captain-P-Goldfish** [comment]
Honestly I would start to love you if you would provide an eclipse formatter configuration or an intellij formatter configuration...

**Comment by DMHP** [comment]
@Captain-P-Goldfish 
Please create a xml file with the following content and import it to intellij  as the code style.

<code_scheme name="wso2_code_style" version="173">
  <JavaCodeStyleSettings>
    <option name="CLASS_COUNT_TO_USE_IMPORT_ON_DEMAND" value="50" />
    <option name="NAMES_COUNT_TO_USE_IMPORT_ON_DEMAND" value="50" />
    <option name="IMPORT_LAYOUT_TABLE">
      <value>
        <package name="" withSubpackages="true" static="false" />
        <emptyLine />
        <package name="java" withSubpackages="true" static="false" />
        <package name="javax" withSubpackages="true" static="false" />
        <emptyLine />
        <package name="" withSubpackages="true" static="true" />
      </value>
    </option>
  </JavaCodeStyleSettings>
  <XML>
    <option name="XML_LEGACY_SETTINGS_IMPORTED" value="true" />
  </XML>
  <codeStyleSettings language="JAVA">
    <option name="KEEP_BLANK_LINES_IN_DECLARATIONS" value="1" />
    <option name="KEEP_BLANK_LINES_IN_CODE" value="1" />
    <option name="KEEP_BLANK_LINES_BEFORE_RBRACE" value="1" />
    <option name="BLANK_LINES_BEFORE_METHOD_BODY" value="1" />
    <option name="BLANK_LINES_AFTER_CLASS_HEADER" value="1" />
  </codeStyleSettings>
  <codeStyleSettings language="JSP">
    <indentOptions>
      <option name="SMART_TABS" value="true" />
      <option name="KEEP_INDENTS_ON_EMPTY_LINES" value="true" />
    </indentOptions>
  </codeStyleSettings>
</code_scheme>

**Pull request merged**
